# -*- coding: utf-8 -*-
"""Untitled2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19aA6-Aeesl4Q82X9uDfGo5Sofg5mPHxp
"""

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image, ImageOps

st.set_page_config(page_title="Car/Bike Classifier", layout="centered")

@st.cache_resource
def load_model():
    try:
        return tf.keras.models.load_model('car_bike_model.keras')
    except Exception as e:
        st.error(f"Error loading model: {e}")
        st.info("Please ensure your trained model is saved as 'car_bike_model.keras' in the same directory.")
        return None

model = load_model()

class_names = ['Bike', 'Car']

st.title("Bike or Car Classifier")
st.write("Upload an image to determine if it is a motorcycle or a car.")

file = st.file_uploader("Upload a vehicle image", type=["jpg", "jpeg", "png", "bmp"])

def import_and_predict(image_data, model):
    """
    Preprocesses the image to match the model's input size and makes a prediction.
    """
    if model is None:
        return None

    size = model.input_shape[1:3]

    image = ImageOps.fit(image_data, size, Image.LANCZOS)

    img_array = np.asarray(image).astype('float32') / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    prediction = model.predict(img_array)
    return prediction

if file is None:
    st.info("Please upload an image of a car or bike to proceed.")
elif model is not None:
    image = Image.open(file).convert('RGB')
    st.image(image, caption="Uploaded Image", use_container_width=True)

    with st.spinner("Analyzing image..."):
        prediction = import_and_predict(image, model)

    predicted_index = int(np.argmax(prediction))
    predicted_class = class_names[predicted_index]
    confidence = round(100 * np.max(prediction), 2)

    st.markdown(f"### 🏁 Predicted Vehicle Type: **{predicted_class}**")
    st.markdown(f"Confidence: `{confidence}%`")

    if predicted_class == 'Car':
        st.success("Classification successful! This looks like a Car.")
    elif predicted_class == 'Bike':
        st.success("lassification successful! This looks like a Motorcycle/Bike.")
    else:
        st.info("The model detected something, but it's inconclusive.")

    st.subheader("Model Probabilities")
    prob_df = pd.DataFrame({
        'Class': class_names,
        'Probability (%)': prediction[0] * 100
    }).sort_values(by='Probability (%)', ascending=False)
    st.dataframe(prob_df, hide_index=True)
